- hosts: challange-terraform-ansible
  tasks:
  - name: Installing python3 and python3-virtualenv
    apt:
      pkg:
      - python3
      - python3-virtualenv
      update_cache: yes
    become: yes
  - name: Installing pip dependencies (Django and Django Rest)
    pip:
      virtualenv: /home/ubuntu/vpc/venv
      name:
        - django
        - djangorestframework
  - name: Starting the Django Project
    shell: '. /home/ubuntu/vpc/venv/bin/activate; django-admin startproject setup /home/ubuntu/vpc'
  - name: Allowing all hosts on settings
    lineinfile:
      path: /home/ubuntu/vpc/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes
  - name: Running the server
    shell: '. /home/ubuntu/vpc/venv/bin/activate; python3 /home/ubuntu/vpc/manage.py runserver 0.0.0.0:8080'
