---
- name: Configurar servidor WordPress
  hosts: wordpress
  become: true
  tasks:

    - name: Instalar pacotes necessários
      yum:
        name:
          - httpd
          - php
          - php-mysqlnd
          - mariadb105
        state: present

    - name: Iniciar e habilitar Apache
      service:
        name: httpd
        state: started
        enabled: true

    - name: Baixar WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Extrair WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes

    - name: Configurar arquivo wp-config.php
      template:
        src: templates/wp-config.php.j2
        dest: /var/www/html/wordpress/wp-config.php
        owner: apache
        group: apache
        mode: '0644'

    - name: Ajustar permissões
      file:
        path: /var/www/html/wordpress
        owner: apache
        group: apache
        recurse: yes
